 version: "3.5"

 services:
   api:
     restart: unless-stopped
     build:
       context: .
     ports:
       - "8080:80"
     environment:
       ECOFOREST_URL: http://ecoforest
       #ECOFOREST_USERNAME: xxx
       #ECOFOREST_PASSWORD: yyy
